name: tcli Test

on:
  push:
    branches: ["main"]
    paths:
      - "tools/tangle-cli/**"
      - ".github/workflows/tcli-test.yaml"
  pull_request:
    types: [opened, synchronize]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: npm 7
        run: npm install -g npm@7
      - name: Tool code build
        run: |
          npm install
          npm run build-tcli
